### PR TITLE
Implement "Last Match" chart

### LINKED ISSUE #83: [details/last match]: Implement template for "Last match section"
- Implement template
- Remove placeholder picture
- Add data
- Add template as to /details.html template

### PR DESCRIPTION
**Pull request by pinpox**
fixes #83

### CODE REVIEW

**Comment by moritzpflueger** [comment]
notice that `Wins (T) + Wins (CT) > Total Wins`

image

My current calculation for the outcome propery checks `total Wins ><= total Rounds`

I find this confusing, what's the expected behaviour?

**Comment by pinpox** [comment]
> My current calculation for the outcome propery checks `total Wins ><= total Rounds`
> 
> I find this confusing, what's the expected behaviour?

- Rounds Total: How many rounds the last match took in total
- Rounds won (all): How many rounds the player won in the last match in both halftimes together
- Rounds won (CT): How many rounds the player won in the last match during the CT side
- Rounds won (T): How many rounds the player won in the last match during the T side
- Outcome: "win" if rounds won > rounds total/2,   "loose" if rounds won < rounds total/2, draw if rounds won == rounds total /2

**Comment by pinpox** [comment]
I merged the master into this branch to resolve merge conflicts.

**Comment by pinpox** [comment]
> I merged the master into this branch to resolve merge conflicts.

again.

**Pull request merged**
