### PR TITLE
add viewport tag for mobile

### PR DESCRIPTION
**Pull request by moritzpflueger**
breaks some layouts on mobile, but those should be fixed anyways IMO

### CODE REVIEW

**Comment by pinpox** [comment]
@moritzpflueger I don't fully understand what this does. AFAIK the materialize lib used is already mobile-ready. Could you elaborate what this PR does and why it's needed?

**Comment by moritzpflueger** [comment]
well, I'm not 100% sure. It "tricks" a mobile browser to zoom into the website. 

This is generally done, because modern Smartphones have roughly the same resolution as Laptop Screens, while being way smaller.

compare with https://developer.mozilla.org/de/docs/Mozilla/Mobile/Viewport_meta_tag#:~:text=The%20initial%2Dscale%20property%20controls,the%20page%20in%20or%20out.

But you're right. The css framework should take care of this. If you want I cant further investigate in my next working session.

| with intial scale | without scaling viewport |
|---|---|
| image  |  image |

**Comment by moritzpflueger** [comment]
closes #98

**Comment by moritzpflueger** [comment]
##### turns out viewport must be included explicitely by design:
```html
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>

      <!--JavaScript at end of body for optimized loading-->
      <script type="text/javascript" src="js/materialize.min.js"></script>
    </body>
  </html>
```

source: [getting started from official materialize docs](https://materializecss.com/getting-started.html)

**Comment by pinpox** [comment]
We should put it in then, good catch.

**Pull request merged**
