### PR TITLE
Implement weapon charts and table

### LINKED ISSUE #85: [details/weapons]: Implement weapon charts and table
image

- Replace pie-chart with new library
- Fill in missing table values
- Prettify table with colors and icons
- Remove placeholder graphic

### PR DESCRIPTION
**Pull request by moritzpflueger**
closes #85

### CODE REVIEW

**Comment by pinpox** [comment]
@moritzpflueger make sure you have no merge conflicts before requesting merge. 

```
git checkout master 
git pull                                                              #pull down latest master changes
git checkout implement-weapon-charts-table  #checkout your branch
git merge master                                              #merge master into implement-weapons-chart-table
```

**Comment by moritzpflueger** [comment]
@pinpox can you give me a briefing about data handling? would like to have a dynamic solution for the weapons table instead of handcoding everything myself

**Comment by pinpox** [comment]
Not sure if this we can generate the table dynamically in this case, since every entry has it's own icon and name. The database saves/provides only shortnames for the weapons, not the full name and no icons. Since CS:GO only has 34 weapons, it might be easier to just put them in the table once by hand. The icons should all be in the `public/icons` folder (look at the code for the already existing entries)

**Comment by pinpox** [comment]
@moritzpflueger I pulled the latest commit from `implement-weapon-charts-table` but something seems to be wrong, the weapon icons are huge: 

image

**Comment by moritzpflueger** [comment]
i wrote the img-height directly into the html-template. Can you please check if the bug is fixed by doing this?

**Pull request merged**
